/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fansy_mySDK_MainActivity */

#ifndef _Included_com_fansy_mySDK_MainActivity
#define _Included_com_fansy_mySDK_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fansy_mySDK_MainActivity
 * Method:    OnLogin
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_fansy_mySDK_MainActivity_OnLogin
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
